#!/usr/bin/env python
# -*- coding: utf-8 -*-

import xml.dom.minidom
from xml.sax.saxutils import escape

def prettyPrint(xmlString):
	x = xml.dom.minidom.parseString(xmlString)
	return x.toprettyxml()

def elem(e, t, attr = {}):
	attr = " ".join(['%s="%s"'%(k, v) for (k,v) in attr.items()])
	return "<%s %s>%s</%s>\n" % (e, attr, t, e) if len(attr) else  "<%s>%s</%s>\n" % (e, t, e)

def toA(n, href):
	return elem("a", n, {"href": href})

def toUl(l):
	return elem("ol", "".join([elem("li", x) for x in l]))

def toP(c):
	return elem("p", c)

def write(name, content):
	print "writing", name
	with open(name, "w") as f:
		f.write(content)
		
def navigation(meta, l, r = None):
	"""eg navigation(meta, ("<< Prev", "foo.html"))"""
	l = [
			(meta["seminarSubject"], meta["seminarLink"]),
			(meta["seminar"], "index.html"),
			l
		]
	if r is not None:
		l.append(r)
	bareList = [ "[ %s ]" % toA(n, l) for (n,l) in l]
	bare = "<hr /> ... %s ... <hr />" % " ... ".join(bareList)
	return elem("div", bare)

def sectionToNaviElem(section, prefix = "", postfix = ""):
	return (prefix + section["name"] + postfix, sectionToFileName(section))
		
def sectionToFileName(section):
	return section["name"].lower() + ".html"

colorize = """
<script language="JavaScript">
function colorize(){
	var cWords = ["int", "bool", "return", "false", "true", "if"]
	var keywords = {
		"csharp":		cWords.concat(["from", "in", "where", "select", "var", "=&gt;", "string", "public", "private", "static", "this", "interface", "class", "new", "null", "as"]),
		"cpp":			cWords.concat(["class"]),
		"javascript":	cWords.concat(["function", "var", "new", "Object", "Array", "null", "typeof"]),
		"haskell":		["-&gt;", "::", "data", "do", "&lt;-"],
		"ruby":			["class", "New", "new", "def", "end", "require", "module"]
	}


	for (lang in keywords) {
		var words = keywords[lang]
		var element = document.getElementsByClassName(lang);
		for( var i=0; i<element.length; i++ ) {
			var newHTML = element[i].innerHTML;

			for( var j=0; j<words.length; j++ ) {
				newHTML = newHTML.replace(new RegExp("(^|\\\s|\\\.|\\\(|\\\{)(" + words[j] + ")(?=\\\s|\\\.|\\\(|\\\)|\\\;|\\\[|$)", "g"),'$1<span style="color:blue">$2</span>');
			}
			element[i].innerHTML = newHTML;
		}
	}
}
onload=colorize
</script>
"""
def head(meta):
	return ("""
<head>
	<title>Seminar - %(seminar)s</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="author" content="%(author)s" />
	<style type="text/css"><!--
	p {width:50em;}
	span {font-family: monospace;}
	pre
	{
		-moz-tab-size: 4;
		-o-tab-size:   4;
		tab-size:      4;
	}
	--!></style>
</head>""" % meta) + colorize

def footer():
	return """
	<div style="font-size:70%">generated by <a href="https://github.com/sebastian-philipp/schmidt-doku-generator">schmidt-doku-generator</a> (GitHub)</div>"""


# index

def frameIndex(meta):
	"""usage {"seminar": seminar, "desc": desc, "author":author}"""
	meta["navi"] = navigation(meta, ("Inhaltsverzeichnis", "contents.html"))
	meta["head"] = head(meta)
	meta["footer"] = footer()
	return """
<html>
%(head)s
<body>
	<a name="top"></a>
	<div align="center">
		<h1>%(seminar)s</h1>
	</div>
%(navi)s
	<div align="center">
		<h1>%(seminar)s</h1>
		<p>%(desc)s</p>
		<p>%(author)s</p>
	</div>
%(navi)s
%(footer)s
</body>	
</html>
""" % meta 

# contents

def frameContents(meta, content):
	meta["navi"] = navigation(meta, ("<< Startseite", "index.html"), sectionToNaviElem(content[0], "", " >>"))
	meta["head"] = head(meta)
	meta["toContentsList"] = toContentsList(content)
	meta["footer"] = footer()
	return """
<html>
%(head)s
<body>
	<a name="top"></a>
	<div align="center">
		<h1>Inhaltsverzeichnis</h1>
	</div>
%(navi)s
	<div>
%(toContentsList)s
	</div>
%(navi)s
%(footer)s
</body>	
</html>"""% meta

def sectiontoUl(section):
	sectionLinkName = sectionToFileName(section)
	def dictToName(subSection):
	#	print "subSection", subSection
		return subSection["name"]
	#print "section", section
	names = map(dictToName,section["content"])
	for i in range(len(names)):
		names[i] = toA(names[i], sectionLinkName + "#" + str(i))
	return toA(section["name"], sectionLinkName) + toUl(names)

def toContentsList(content):
	return toUl(map(sectiontoUl, content))

# section.html

def writeSubSections(meta, content):
	contentNaviElem = ("Inhaltsverzeichnis", "contents.html")
	
	for i in range(len(content)):
		prev = sectionToNaviElem(content[i-1], "<< ", "") if i > 0 else contentNaviElem
		next = sectionToNaviElem(content[i+1], "", " >>") if i < (len(content)-1) else contentNaviElem
		write(sectionToFileName(content[i]), frameSubSection(meta, prev, next, content[i]))

def frameSubSection(meta, prev, next, subSection):
	subSection["head"] = head(meta)
	subSection["navi"] = navigation(meta, prev, next)
	subSection["desc"] = toP(prettyText(subSection["desc"]))
	subSection["subSections"] = ""
	subSection["footer"] = footer()
	for i in range(len(subSection["content"])):
		subSection["subSections"] += toSubSection(i, subSection["content"][i])

	return """
<html>
%(head)s
<body>
	<a name="top"></a>
	<div align="center">
		<h1>%(name)s</h1>
	</div>
%(navi)s
	<div>
%(desc)s
%(subSections)s
	</div>
%(navi)s
%(footer)s
</body>	
</html>
""" % subSection

def prettyText(text):
	def handlePrefix(l, context):
		if context is None:
			context = {"inPre":False, "inTable":False}
		if l.startswith("\\h4"):
			l = elem("h4", l[3:])
		elif l.startswith("\\a"):
			l = toA(l[2:], l[2:]) + "<br>"
		elif l.startswith("\\code{"):
			context["inPre"] = True
			l = "</p><pre>" + l[7:]
		elif l.startswith("\\code-"):
			context["inPre"] = True
			lang, rest = l[6:].split("{",1)
			l = "</p><pre class="+lang+">" + rest
		elif l.startswith("\\code}"):
			context["inPre"] = False
			l = "</pre><p>" + l[7:]
		elif l.startswith("\\table{"):
			context["inTable"] = True
			l = "</p><table border='1'>" + l[8:]
		elif l.startswith("\\table}"):
			context["inTable"] = False
			l = "</table><p>" + l[8:]
		elif not context["inPre"] and not context["inTable"]:
			l += "<br>"
		return (l, context)

	context = None
	newText = []
	for l in text.splitlines():
		(ll, context) = handlePrefix(l, context)
		newText.append(ll)
	return "\n".join(newText)

def toSubSection(number, subSection):
	subSection["number"] = number
	subSection["content"] = toP(prettyText(subSection["content"]))
	return """
		<hr />
		<h2><a name="%(number)s">%(name)s</a></h2>
%(content)s
""" % subSection

def main(meta, content):
	write("index.html", frameIndex(meta))
	write("contents.html", frameContents(meta, content))
	writeSubSections(meta, content)





